FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile

COPY . .

RUN pnpm run build-storybook

FROM nginx:alpine AS runner
COPY --from=base /app/storybook-static /usr/share/nginx/html
EXPOSE 6006

# Custom Nginx port configuration for 6006
RUN sed -i 's/listen       80;/listen       6006;/g' /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
