packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  protobufjs: set this to true or false
