packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  '@firebase/util': true
  '@parcel/watcher': true
  '@swc/core': true
  protobufjs: true
  core-js-pure: true
  esbuild: true
