import { Property } from '@/types/property';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    slug: 'sky-collection-penthouse-downtown',
    title_en: 'Sky Collection Penthouse',
    title_ar: 'بنتهاوس سكاي كوليكشن',
    description_en:
      'Ultra-luxury penthouse featuring panoramic views of Burj Khalifa and Dubai Fountain with private infinity pool.',
    description_ar:
      'بنتهاوس فائق الفخامة مع إطلالات بانورامية على برج خليفة ونافورة دبي مع مسبح خاص.',
    price: 18250000,
    price_verified: true,
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 6500,
    community: 'Downtown Dubai',
    sub_community: 'Opera District',
    property_type: 'penthouse',
    tenure: 'ready',
    developer: 'Emaar Properties',
    completion_date: '2024-01-01',
    service_charge_aed: 24,
    cap_rate_percentage: 6.8,
    est_annual_rental: 1241000,
    images: [
      '/images/properties/property-penthouse.jpg',
      '/images/properties/property-apartment.jpg',
    ],
    thumbnail: '/images/properties/property-penthouse.jpg',
    latitude: 25.1972,
    longitude: 55.2744,
    features: ['Private Pool', 'Burj Khalifa View', 'Escrow Verified'],
    amenities: ['Gym', 'Concierge', 'Valet Parking'],
    verification_status: 'verified',
    verification_source: 'DLD REST API',
    is_featured: true,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prop-2',
    slug: 'modern-palm-jumeirah-beachfront-villa',
    title_en: 'Modern Beachfront Villa',
    title_ar: 'فيلا حديثة على الواجهة البحرية',
    description_en:
      'Contemporary beachfront mansion on the Fronds of Palm Jumeirah with private beach access.',
    description_ar:
      'قصر عصري على الواجهة البحرية في سعف نخلة جميرا مع وصول خاص للشاطئ.',
    price: 45000000,
    price_verified: true,
    bedrooms: 6,
    bathrooms: 7,
    area_sqft: 10000,
    community: 'Palm Jumeirah',
    sub_community: 'Frond N',
    property_type: 'villa',
    tenure: 'ready',
    developer: 'Nakheel',
    completion_date: '2023-06-01',
    service_charge_aed: 18,
    cap_rate_percentage: 5.5,
    est_annual_rental: 2475000,
    images: ['/images/properties/property-villa.jpg'],
    thumbnail: '/images/properties/property-villa.jpg',
    latitude: 25.1124,
    longitude: 55.139,
    features: ['Private Beach', 'Infinity Pool', 'Smart Home'],
    amenities: ['Private Dock', 'Security', 'Landscaped Garden'],
    verification_status: 'verified',
    verification_source: 'DLD REST API',
    is_featured: true,
    is_active: true,
    created_at: '2026-01-02T00:00:00Z',
    updated_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'prop-3',
    slug: 'emirates-hills-golf-estate',
    title_en: 'Ultra Luxury Mansion',
    title_ar: 'قصر تلال الإمارات الفاخر',
    description_en:
      'Palatial estate overlooking championship golf course with classic Mediterranean architecture.',
    description_ar:
      'قصر فاخر يطل على ملعب الجولف العالمي مع هندسة معمارية متوسطية.',
    price: 120000000,
    price_verified: true,
    bedrooms: 8,
    bathrooms: 10,
    area_sqft: 25000,
    community: 'Emirates Hills',
    sub_community: 'Sector E',
    property_type: 'villa',
    tenure: 'ready',
    developer: 'Emaar Properties',
    completion_date: '2022-01-01',
    service_charge_aed: 15,
    cap_rate_percentage: 4.8,
    est_annual_rental: 5760000,
    images: ['/images/properties/property-villa.jpg'],
    thumbnail: '/images/properties/property-villa.jpg',
    latitude: 25.0683,
    longitude: 55.1764,
    features: ['Golf Course View', 'Private Cinema', 'Basement Garage'],
    amenities: ['Spa', 'Tennis Court', 'Wine Cellar'],
    verification_status: 'verified',
    verification_source: 'DLD REST API',
    is_featured: true,
    is_active: true,
    created_at: '2026-01-03T00:00:00Z',
    updated_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'prop-4',
    slug: 'marina-gate-waterfront-residence',
    title_en: 'Marina Gate Residence',
    title_ar: 'شقة فاخرة في مارينا جيت',
    description_en:
      'High-floor waterfront apartment with floor-to-ceiling glass windows and yacht marina view.',
    description_ar:
      'شقة في طابق مرتفع على الواجهة البحرية مع إطلالة كاملة على مرسى اليخوت.',
    price: 6800000,
    price_verified: true,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2400,
    community: 'Dubai Marina',
    sub_community: 'Marina Gate',
    property_type: 'apartment',
    tenure: 'ready',
    developer: 'Select Group',
    completion_date: '2023-01-01',
    service_charge_aed: 20,
    cap_rate_percentage: 7.2,
    est_annual_rental: 489600,
    images: ['/images/properties/property-apartment.jpg'],
    thumbnail: '/images/properties/property-apartment.jpg',
    latitude: 25.0865,
    longitude: 55.1432,
    features: ['Marina View', 'Balcony', 'Fully Furnished'],
    amenities: ['Infinity Pool', 'Gym', 'Squash Court'],
    verification_status: 'verified',
    verification_source: 'DLD REST API',
    is_featured: true,
    is_active: true,
    created_at: '2026-01-04T00:00:00Z',
    updated_at: '2026-01-04T00:00:00Z',
  },
];
